version: '3'
services:
  appacc:
    build:
      context: AcceptMessage
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - my-network
  applog:
    build:
      context: LogonPage
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-network
    restart: unless-stopped
  databasecontroller:
    build:
      context: DatabaseController
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
  

networks:
  my-network:

volumes:
  postgres:
  pgadmin:
